version: '3'
services:
  replica0:
    image: myapp:latest
    ports:
      - "11000:11000"
    command: java -Dlogback.configurationFile="./config/logback.xml" -jar /app/ReplicaServer-jar-with-dependencies.jar 0
    networks:
      - app-network
  replica1:
    image: myapp:latest
    ports:
      - "11010:11010"
    command: java -Dlogback.configurationFile="./config/logback.xml" -jar /app/ReplicaServer-jar-with-dependencies.jar 1
    networks:
      - app-network
  replica2:
    image: myapp:latest
    ports:
      - "11020:11020"
    command: java -Dlogback.configurationFile="./config/logback.xml" -jar /app/ReplicaServer-jar-with-dependencies.jar 2
    networks:
      - app-network
  replica3:
    image: myapp:latest
    ports:
      - "11030:11030"
    command: java -Dlogback.configurationFile="./config/logback.xml" -jar /app/ReplicaServer-jar-with-dependencies.jar 3
    networks:
      - app-network
  proxy:
    image: myapp:latest
    ports:
      - "3456:3456"
    command: java -Dlogback.configurationFile="./config/logback.xml" -jar /app/RestWalletServer-jar-with-dependencies.jar
    networks:
      - app-network
networks:
  app-network:
    driver: bridge